"""Repository Protocol — 定义持久化契约，实现方在 infra/ 层"""

from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol, runtime_checkable

from ..cognitive.models import (
    EdgeRevision,
    NodeRevision,
    RetrievalScope,
    RingHealth,
    TreeManifest,
)
from ..evaluation.models import Evaluation
from ..runtime.models import AgentRun, ActionResult, RunEdgeReference, RunNodeReference
from ..soil.models import SoilEvent


@runtime_checkable
class TreeRepository(Protocol):
    async def create(self, tree: TreeManifest) -> str: ...
    async def get(self, tree_id: str) -> Optional[TreeManifest]: ...
    async def list(self, tenant_id: str = "default") -> List[TreeManifest]: ...
    async def update_active_ring(self, tree_id: str, ring_id: str) -> None: ...


@runtime_checkable
class RevisionRepository(Protocol):
    async def create_node(self, rev: NodeRevision) -> str: ...
    async def create_edge(self, rev: EdgeRevision) -> str: ...
    async def get_node(self, revision_id: str) -> Optional[NodeRevision]: ...
    async def get_edge(self, revision_id: str) -> Optional[EdgeRevision]: ...
    async def list_by_ids(self, revision_ids: List[str]) -> List[NodeRevision]: ...
    async def list_active_for_ring(
        self, ring_id: str, scope: RetrievalScope
    ) -> List[NodeRevision]: ...
    async def list_edges_for_ring(self, ring_id: str) -> List[EdgeRevision]: ...
    async def get_latest_node_revision(self, node_id: str) -> Optional[NodeRevision]: ...
    async def get_latest_edge_revision(self, edge_id: str) -> Optional[EdgeRevision]: ...
    async def list_all_active(self, tree_id: Optional[str] = None, limit: int = 10000, offset: int = 0) -> List[NodeRevision]: ...


@runtime_checkable
class RingRepository(Protocol):
    async def create(self, ring) -> str: ...
    async def get(self, ring_id: str) -> Optional[Any]: ...
    async def add_node_mapping(self, ring_id: str, node_id: str, revision_id: str) -> None: ...
    async def add_edge_mapping(self, ring_id: str, edge_id: str, revision_id: str) -> None: ...
    async def get_node_mappings(self, ring_id: str) -> Dict[str, str]: ...
    async def get_edge_mappings(self, ring_id: str) -> Dict[str, str]: ...
    async def seal(self, ring_id: str) -> None: ...
    async def activate(self, ring_id: str) -> None: ...
    async def rollback(self, ring_id: str) -> None: ...
    async def set_health(self, ring_id: str, health: RingHealth) -> None: ...


@runtime_checkable
class SoilRepository(Protocol):
    async def append_event(self, event: SoilEvent) -> str: ...
    async def get_event(self, event_id: str) -> Optional[SoilEvent]: ...
    async def get_event_by_idempotency_key(self, tenant_id: str, idempotency_key: str) -> Optional[SoilEvent]: ...
    async def list_after_checkpoint(self, checkpoint: int, limit: int = 100) -> List[SoilEvent]: ...


@runtime_checkable
class RunRepository(Protocol):
    async def create(self, run: AgentRun) -> str: ...
    async def get(self, run_id: str) -> Optional[AgentRun]: ...
    async def add_node_reference(self, ref: RunNodeReference) -> None: ...
    async def add_edge_reference(self, ref: RunEdgeReference) -> None: ...
    async def add_action_result(self, result: ActionResult) -> str: ...
    async def finish(self, run_id: str, status: str, result_ref: Optional[str] = None) -> None: ...
    async def list_by_status(self, status: str, limit: int = 50) -> List[AgentRun]: ...
    async def list_node_references(self, run_id: str) -> List[Dict[str, Any]]: ...
    async def list_edge_references(self, run_id: str) -> List[Dict[str, Any]]: ...
    async def list_action_results(self, run_id: str) -> List[Dict[str, Any]]: ...


@runtime_checkable
class EvaluationRepository(Protocol):
    async def create(self, evaluation: Evaluation) -> str: ...
    async def list_by_run(self, run_id: str) -> List[Evaluation]: ...


@runtime_checkable
class OutboxRepository(Protocol):
    async def enqueue(self, aggregate_type: str, aggregate_id: str, operation: str, payload: Optional[Dict] = None) -> str: ...
    async def claim(self, batch_size: int = 10) -> List[Any]: ...
    async def mark_done(self, outbox_id: str) -> None: ...
    async def mark_failed(self, outbox_id: str, error: str) -> None: ...
